title: Pravitha Pratheep # your name (or website title) here

logo: "/images/Uxfolpic.jpg?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  Delighted to see you here, thank you for visiting. My name is Pravitha but you call me Vi(pronounced like the alphabet 'V').
  <br><br>
  I am currently in my senior year at Seattle Pacific University studying Information Systems. I will be graduating in June 2021 and I am actively seeking for full time opportunities in the world of tech!
 <br><br>
 In the everchanging and forward moving world,challenges certainly do arise for people like you and me. I aspire to solve challenges with sensible and humane solutions that are equitable and approachable friendly for users.
  <br><br>
  In my free time, I love to bake and experiment making different versions of coffees at home. Aside from baking and drinking a lot of coffee, I practice yoga.
  <br><br>
  <a href="https://www.linkedin.com/in/jiexieow/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
