title: Pravitha Pratheep # your name (or website title) here

logo: "/images/icon.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A senior student at Seattle Pacific University majoring in Information Systems
  with an expected graduation at June 2021.
  <br><br>
  An enthusiastic Information System student at Seattle Pacific University seeking full-time opportunities or internships for Summer 2021!
  <br><br>
  Wanting to give back to the community
  <br><br>
  <a href="https://www.linkedin.com/in/jiexieow/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
